### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by RNSolutionKhan** [MasayukiSuda/GPUVideo-android#103]
java.lang.RuntimeException: Could not link program
        at .camera.egl.EglUtil.createProgram(EglUtil.java:61)
        at .camera.egl.filter.GlFilter.setup(GlFilter.java:78)

Hi sir the app is crashing in Android 12

**Comment by neerajrcodiant** [comment]
Have you fixed this issue? , on which device you are facing this issue
