### ISSUE TITLE
issue on saving

### ISSUE THREAD

**Issue by jy617lee** [MasayukiSuda/GPUVideo-android#17]
Hi, Thank you for this amazing library!

However, I just run sample app of this project, and found that if I follow the flow below, causes error. 
movie preview --> select filter --> touch save button 

2019-06-29 15:04:46.207 12432-12643/com.daasuu.gpuvideoandroid E/AndroidRuntime: FATAL EXCEPTION: GLThread 30908
    Process: com.daasuu.gpuvideoandroid, PID: 12432
    java.lang.IllegalStateException: Could not get attrib or uniform location for center
        at com.daasuu.gpuv.egl.filter.GlFilter.getHandle(GlFilter.java:153)
        at com.daasuu.gpuv.egl.filter.GlBulgeDistortionFilter.onDraw(GlBulgeDistortionFilter.java:77)
        at com.daasuu.gpuv.egl.filter.GlFilter.draw(GlFilter.java:121)
        at com.daasuu.gpuv.player.GPUPlayerRenderer.onDrawFrame(GPUPlayerRenderer.java:162)
        at com.daasuu.gpuv.egl.GlFrameBufferObjectRenderer.onDrawFrame(GlFrameBufferObjectRenderer.java:58)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

These are the error logs, 
and this is caused because below two methods returns -1
```GLES20.glGetAttribLocation(program, name);
GLES20.glGetUniformLocation(program, name);```

Do you have any idea that I can fix this issue?

**Comment by jy617lee** [comment]
I found how to resolve this! I don't know why, but if I delete below code in Glfilter.java (release()), it works!

```handleMap.clear();```

**Comment by Jobeeapk** [comment]
Hi. I have the same issue. How to edit this code when I use library as dependency?

**Comment by MasayukiSuda** [comment]
Thank you for a good discussion.

**Comment by BilalAsif25** [comment]
@jy617lee Hi, does it have any impact on the app, i mean any new crashes by commenting this `handleMap.clear();`

**Comment by cuk2dn95** [comment]
> Hi. I have the same issue. How to edit this code when I use library as dependency? PS: Problem seems to be solved. I'm creating new GLFilter object for generate video. Previously I'm was using same filter which was used to add filter to preview.

Thanks you, you save my day
