### ISSUE TITLE
GlWhiteBalanceFilter does't work

### ISSUE THREAD

**Issue by Stasyan123** [MasayukiSuda/GPUVideo-android#31]
An error occurred while using this filter:

`Process: com.sm.stasversion, PID: 11011
    java.lang.RuntimeException: Could not link program
        at com.daasuu.gpuv.egl.EglUtil.createProgram(EglUtil.java:61)
        at com.daasuu.gpuv.egl.filter.GlFilter.setup(GlFilter.java:77)
        at com.daasuu.gpuv.player.GPUPlayerRenderer.onDrawFrame(GPUPlayerRenderer.java:141)
        at com.daasuu.gpuv.egl.GlFrameBufferObjectRenderer.onDrawFrame(GlFrameBufferObjectRenderer.java:58)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
2019-11-18 14:55:18.931 11570-11570/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2019-11-18 14:55:18.932 11570-11570/? E/Zygote: accessInfo : 1
2019-11-18 14:55:18.951 11570-11570/? E/android.dqagen: Not starting debugger since process cannot load the jdwp agent.
2019-11-18 14:55:18.964 11582-11582/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2019-11-18 14:55:18.966 11582-11582/? E/Zygote: accessInfo : 1`

Apparently, an error occurs in this place:

`public static int createProgram(final int vertexShader, final int pixelShader) throws GLException {
        final int program = glCreateProgram();
        if (program == 0) {
            throw new RuntimeException("Could not create program");
        }

        GLES20.glAttachShader(program, vertexShader);
        GLES20.glAttachShader(program, pixelShader);

        GLES20.glLinkProgram(program);
        final int[] linkStatus = new int[1];
        GLES20.glGetProgramiv(program, GL_LINK_STATUS, linkStatus, 0);
        if (linkStatus[0] != GL_TRUE) {
            GLES20.glDeleteProgram(program);
            throw new RuntimeException("Could not link program");
        }
        return program;
    }` - EglUtil.java file.

In case of using a this filter, the pixelShader variable value = 0.

Thanks in advance.

**Comment by Link184** [comment]
Got the same error on all emulators and some devices

**Comment by aahanverma00710** [comment]
Did it work or could you please tell me how to add it I am facing the same issue
