### ISSUE TITLE
MediaCodec$CodecException: Error 0xfffffc0e

### ISSUE THREAD

**Issue by jaypalrana** [MasayukiSuda/GPUVideo-android#67]
I am continuously getting the following exception in the Redmi 6 Pro device with Android version 9.
```
2020-09-24 13:01:41.548 7050-7634/com.tristate.smylee E/ACodec: [OMX.qcom.video.encoder.avc] failed to set input port definition parameters.
2020-09-24 13:01:41.548 7050-7634/com.tristate.smylee W/ExtendedACodec: Failed to get extension for extradata parameter
2020-09-24 13:01:41.548 7050-7634/com.tristate.smylee E/ACodec: [OMX.qcom.video.encoder.avc] configureCodec returning error -1010
2020-09-24 13:01:41.548 7050-7634/com.tristate.smylee E/ACodec: signalError(omxError 0x80001001, internalError -1010)
2020-09-24 13:01:41.548 7050-7633/com.tristate.smylee E/MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
2020-09-24 13:01:41.550 7050-7050/com.tristate.smylee E/MediaCodec: configure failed with err 0xfffffc0e, resetting...
2020-09-24 13:01:41.558 7050-7634/com.tristate.smylee I/OMXClient: IOmx service obtained
2020-09-24 13:01:41.658 7050-7050/com.tristate.smylee W/System.err: android.media.MediaCodec$CodecException: Error 0xfffffc0e
2020-09-24 13:01:41.661 7050-7050/com.tristate.smylee W/System.err:     at android.media.MediaCodec.native_configure(Native Method)
2020-09-24 13:01:41.661 7050-7050/com.tristate.smylee W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:1960)
2020-09-24 13:01:41.661 7050-7050/com.tristate.smylee W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:1889)
2020-09-24 13:01:41.661 7050-7050/com.tristate.smylee W/System.err:     at com.daasuu.gpuv.camerarecorder.capture.MediaVideoEncoder.prepare(MediaVideoEncoder.java:128)
2020-09-24 13:01:41.661 7050-7050/com.tristate.smylee W/System.err:     at com.daasuu.gpuv.camerarecorder.capture.MediaMuxerCaptureWrapper.prepare(MediaMuxerCaptureWrapper.java:35)
2020-09-24 13:01:41.662 7050-7050/com.tristate.smylee W/System.err:     at com.daasuu.gpuv.camerarecorder.GPUCameraRecorder$4.run(GPUCameraRecorder.java:273)
2020-09-24 13:01:41.662 7050-7050/com.tristate.smylee W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2020-09-24 13:01:41.662 7050-7050/com.tristate.smylee W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2020-09-24 13:01:41.662 7050-7050/com.tristate.smylee W/System.err:     at android.os.Looper.loop(Looper.java:201)
2020-09-24 13:01:41.662 7050-7050/com.tristate.smylee W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6806)
2020-09-24 13:01:41.662 7050-7050/com.tristate.smylee W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-09-24 13:01:41.662 7050-7050/com.tristate.smylee W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
2020-09-24 13:01:41.662 7050-7050/com.tristate.smylee W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2020-09-24 13:01:41.663 7050-7050/com.tristate.smylee I/CameraRecordListener: onRecordError kotlin.Unit
2020-09-24 13:01:41.663 7050-7050/com.tristate.smylee E/GPUCameraRecorder: android.media.MediaCodec$CodecException: Error 0xfffffc0e
```
The logs are getting when I call GPUCameraRecorder?.start(mOutputFilePath) method.
I have another device Samsung M21 with Android OS version 10 and for that working fine.

**Comment by BilalAsif25** [comment]
@jaypalrana Hi, Did you find any solution to this ?

**Comment by tanveerbyn** [comment]
hardwareAccelerated chnage/add this key in manifest

**Comment by DoozyDoz** [comment]
> hardwareAccelerated chnage/add this key in manifest

Does not solve it

**Comment by dondell** [comment]
I still have the same issue here using this video. Any solution?  https://drive.google.com/file/d/1CLL2RR9vQ_hrGCkg3xYGkv-mMm6qNb0m/view?usp=sharing

**Comment by Grandpasoul** [comment]
I have the same issue with a Motorola MotoG30

`MediaCodecInfo: NoSupport [sizeAndRate.support, 1980x1080x30.0] [OMX.qcom.video.decoder.avc, video/avc] [caprip, moto g(30), motorola, 31]`

<img width="743" alt="Captura de pantalla 2022-12-27 a la(s) 12 56 40" src="https://user-images.githubusercontent.com/81314185/209690668-fc57682d-1f24-49e4-930f-af2694ef1106.png">
