### ISSUE TITLE
Issue occuered after upgrade Exoplayer to 2.13.3

### ISSUE THREAD

**Issue by bhavin1994** [MasayukiSuda/GPUVideo-android#84]
java.lang.IllegalStateException: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
        at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1953)
        at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurface(SimpleExoPlayer.java:791)
        at com.daasuu.gpuv.player.GPUPlayerRenderer.onSurfaceCreated(GPUPlayerRenderer.java:94)
        at com.daasuu.gpuv.egl.GlFrameBufferObjectRenderer.onSurfaceCreated(GlFrameBufferObjectRenderer.java:38)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1541)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

**Comment by alpha2048** [comment]
Maybe this is the same issue: 
https://github.com/MasayukiSuda/ExoPlayerFilter/issues/53
