### ISSUE TITLE
Issue on Landscape Video

### ISSUE THREAD

**Issue by harishashloops** [MasayukiSuda/GPUVideo-android#95]
On potrait it is working fine but on Landscape

The error is here
=> E/FiltersActivity: onFailed()
    android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2014)
        at android.media.MediaCodec.configure(MediaCodec.java:1943)
        at com.daasuu.gpuv.composer.VideoComposer.setUp(VideoComposer.java:68)
        at com.daasuu.gpuv.composer.GPUMp4ComposerEngine.compose(GPUMp4ComposerEngine.java:97)
        at com.daasuu.gpuv.composer.GPUMp4Composer$1.run(GPUMp4Composer.java:210)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
   

=> Code on encoding
encoder.configure(outputFormat, null, null, MediaCodec.CONFIGURE_FLAG_ENCODE);
        encoderSurface = new EncoderSurface(encoder.createInputSurface());
        encoderSurface.makeCurrent();
        encoder.start();
        encoderStarted = true;
        encoderOutputBuffers = encoder.getOutputBuffers();

**Comment by telestia** [comment]
Did you find  solution? Can you share?

**Comment by pablogeek** [comment]
@harishashloops did you fix it?
